[project]
name = "powerco-churn"
version = "0.1.0"
description = ""
authors = [
    {name = "RodolfoPCruz",email = "rodolfo_pinheiro@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "powerco_churn", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
